# Generated by Django 5.1.5 on 2025-01-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_rename_user_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('banner', models.ImageField(upload_to='banners/')),
                ('web', models.URLField()),
            ],
        ),
    ]
